apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dataplatform

resources:
  - namespace.yaml
  - external-services.yaml
  - kafka-statefulset.yaml
  - elasticsearch.yaml
  - airflow.yaml
  - flink.yaml
  - starrocks.yaml
  # TODO: re-enable when AMD64 images available
  # - datalake.yaml
  # - debezium.yaml

commonLabels:
  app.kubernetes.io/part-of: ems-platform
  app.kubernetes.io/managed-by: argocd
