apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dataplatform

resources:
  - namespace.yaml
  - external-services.yaml
  - kafka-statefulset.yaml
  - airflow.yaml
  - flink.yaml
  - openmetadata.yaml
  - starrocks.yaml
  - datalake.yaml

commonLabels:
  app.kubernetes.io/part-of: ems-platform
  app.kubernetes.io/managed-by: argocd
