---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/ingress-nginx.yaml
  - ./manifests/cert-manager.yaml
  - ./manifests/event-service
  - ./manifests/ai-service
  - ./manifests/web-client

namespace: default
