-- Add missing columns to users table for event-service compatibility
ALTER TABLE users ADD COLUMN IF NOT EXISTS firstname TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS lastname TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS cover TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS website_url TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS follower_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS following_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS post_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS events_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS encryption_passcode TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_e2ee_enabled BOOLEAN DEFAULT false;
