---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - networking.yaml
  - external-secrets.yaml
  - dataplatform.yaml
  - web-client.yaml
  - event-service.yaml
  - ai-service.yaml
