---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ems-platform
  annotations:
    argocd.argoproj.io/watch: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/smarteventmanagementsystem/infra.git
    targetRevision: main
    path: manifests/networking
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
